version: "3.9"

services:
  web:
    container_name: web
    image: node:test
    restart: always
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    environment:
      - MONGODB_URI=mongodb://mongo/notesdb
      - PORT=4000
      - NODE_ENV=development
      
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
